name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

resources:
  containers:
    - container: build_container
      image: buildpack-deps:16.04

trigger:
  - master

jobs:
  - job: build_nsmd
    container: build_container
    steps:
      - script: |
          export COMMIT="$(echo $(Build.SourceVersion) | cut -c 1-8)"
          export TAG="${COMMIT}"
          echo "Commit = $COMMIT"
          make docker-nsmd-build
#  - job: build_nsmd_k8s
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_admission_webhook
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_crossconnect_monitor
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_nsmdp
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_icmp_responder_nse
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_vppagent_icmp_responder_nse
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_vppagent_nsc
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_nsc
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_vppagent_dataplane
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_vppagent_dataplane_dev
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: build_vppagent_firewall_nse
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: aks_deploy
#    container: build_container
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: aks_integration_tests
#    container: build_container
#    dependsOn:
#      - build_nsmd
#      - build_nsmd_k8s
#      - build_nsmdp
#      - build_crossconnect_monitor
#      - build_icmp_responder_nse
#      - build_vppagent_icmp_responder_nse
#      - build_vppagent_nsc
#      - build_nsc
#      - build_vppagent_firewall_nse
#      - aks_deploy
#    steps:
#      - script: |
#          pwd
#          ls -la
#  - job: aks_destroy
#    container: build_container
#    dependsOn:
#      - aks_integration_tests
#    condition: always() # destroy AKS cluster even if the integration test job failed
#    steps:
#      - script: |
#          pwd
#          ls -la