

resources:
  containers:
    - container: linux
      image: ubuntu:16.04

trigger:
  - master

jobs:
  - job: build_nsmd
    pool:
      vmImage: 'ubuntu-16.04'
    container: linux
    steps:
      - script: |
          pwd
          ls -la