
pool:
  vmImage: 'ubuntu-16.04'
resources:
  containers:
    - container: linux
      image: ubuntu:16.04

trigger:
  - master

jobs:
  - job: build-nsmd
    container: linux
    steps:
      - script: |
          pwd
          ls -la